<!-- Page d'article de blog détaillé avec les commentaires -->

    	
<article class="contentBlog">
	<h1><?= $posts['title'] ?></h1>
	<h2>Rédigé par <?= $posts['first_name'] ?> <?= $posts['last_name'] ?> le <?= $posts['creation_date'] ?></h2>
	<p><?= $posts['content'] ?></p>
</article>

<div id="theComments">
	
	<?php foreach ($comments as $comment): ?>
	
<hr class="hr">
		<article>
			<h3>Rédigé par <?= $comment['pseudo'] ?> le <?= $comment['creation_date'] ?></h3>
			<p><?= $comment['content'] ?></p>
		</article>
		
	<?php endforeach ?>
</div>
<hr class="hr">

<section id="comments">
	<form id="formComment" >
		<input type="hidden" name="post_id" value="<?= $posts['id'] ?>">
		<ul>
			<li>
				<label for="pseudo">Pseudo :</label>
				<input type="text" id="pseudo" maxlength="50" name="pseudo" value='' autocomplete="off">
			</li>
			<li>
				<label for="content">Commentaire :</label>
				<textarea name="content" maxlength="200" id="content" value=''></textarea>
			</li>
			<li>
				<button class="btnComment">Ajouter</button>
			</li>
		</ul>
	</form>
</section>
