<footer class='footer'>
 <small>Le ProjectWA fabriquer de toute piece par Schmitt Julien ;)</small>
 
</footer>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/bd644ddfa9.js" crossorigin="anonymous"></script>
  <script type="text/javascript" src="../js/formAjax.js"></script>
  <script src="../js/slider.js"></script>
</body>

</html>
