<!doctype html>
<html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta name=viewport content="width=device-width, initial-scale=1">
        <title>ProjetWA</title>
        <link rel="stylesheet" href="../css/normalize.min.css" type="text/css" />
        <link rel="stylesheet" href="../css/style.css" type="text/css" />
    </head>

    <body>
        <header>
            <div id="logo">
                <a href="index.php"><img src="../img/LogoMakr.png"></img></a>
            </div>

            <nav class="menu">
                <ul>
                    <li><a href="index.php">Accueil</a></li>
                    <li><a href="blog.php">Le Blog a JuJu</a></li>
                    <li><a href="realisation.php">Mes Réalisation</a></li>
                    <li><a href="contact.php">Contact</a></li>
                </ul>
            </nav>
        </header>
